import { HINT_FADE_MS, HINT_HOLD_MS, REVEAL_START_MS } from '@/slides/balloon/constants'

export const GALLERY_ACTION_LOCK_MS = 2000
export const GALLERY_BEAT_FADE_MS = 400

export const GALLERY_HINT_FADE_MS = HINT_FADE_MS
export const GALLERY_HINT_HOLD_MS = HINT_HOLD_MS
export const GALLERY_REVEAL_START_MS = REVEAL_START_MS
export const GALLERY_HINT_TOTAL_MS = GALLERY_HINT_FADE_MS + GALLERY_HINT_HOLD_MS + GALLERY_HINT_FADE_MS
